import { useEffect, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import {
  clearAuthToken,
  getAuthToken,
  onAuthFail,
  setAuthToken,
} from "../api/client";
import { resetWebSocket } from "../api/websocket";

/**
 * Gate that ensures the app is only rendered when a plausible auth token
 * is in localStorage.  Before this existed, a missing token caused the
 * REST client to reload the page forever (no login UI existed), which the
 * user saw as the dashboard flickering online/offline.
 *
 * Behavior:
 *   - No token in localStorage -> show the token-input form.
 *   - Token present -> render children.
 *   - Any API call returning 401 -> clear the token, show the form again.
 *
 * The form accepts the PALANTIR_AUTH_TOKEN value printed by the dev
 * launcher (`devtoken` on Mac) or the random token generated by
 * install.sh on the Pi.
 */
export default function AuthGate({ children }: { children: ReactNode }) {
  const [hasToken, setHasToken] = useState<boolean>(() => !!getAuthToken());
  const [input, setInput] = useState("");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Any API call returning 401 drops us back to the form.
    return onAuthFail(() => {
      clearAuthToken();
      setHasToken(false);
      setError("Token rejected by server.  Check the value and try again.");
    });
  }, []);

  const submit = (e: FormEvent) => {
    e.preventDefault();
    const trimmed = input.trim();
    if (!trimmed) {
      setError("Token cannot be empty.");
      return;
    }
    setAuthToken(trimmed);
    setError(null);
    setInput("");
    setHasToken(true);
    // Kick the WS singleton so it reconnects with the new token.
    resetWebSocket();
  };

  if (hasToken) {
    return <>{children}</>;
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">
      <div className="w-full max-w-md bg-white border border-gray-200 rounded-xl shadow-sm p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-lg bg-indigo-600 flex items-center justify-center">
            <span className="text-white font-bold">P</span>
          </div>
          <div>
            <h1 className="text-lg font-semibold">Palantir</h1>
            <p className="text-xs text-gray-500">Enter auth token to continue</p>
          </div>
        </div>

        <form onSubmit={submit} className="space-y-3">
          <label className="block">
            <span className="text-sm font-medium text-gray-700">
              Auth token
            </span>
            <input
              type="password"
              autoFocus
              autoComplete="off"
              spellCheck={false}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="PALANTIR_AUTH_TOKEN"
              className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
            />
          </label>

          {error && (
            <p className="text-sm text-red-600 bg-red-50 border border-red-100 rounded-md px-3 py-2">
              {error}
            </p>
          )}

          <button
            type="submit"
            className="w-full bg-indigo-600 text-white font-medium py-2 rounded-lg hover:bg-indigo-700 transition-colors"
          >
            Continue
          </button>
        </form>

        <p className="mt-4 text-xs text-gray-500 leading-relaxed">
          The token is printed by <code>scripts/dev-up.sh</code> on Mac
          (<code>devtoken</code> by default) or <code>scripts/install.sh</code>{" "}
          on the Pi. It is stored in your browser's localStorage for this
          host and sent as a bearer token with every request.
        </p>
      </div>
    </div>
  );
}
